apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adsb-notifier-config
  namespace: adsb
  labels:
    app.kubernetes.io/name: adsb-notifier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
