"""Shared defaults and limits for ADS-B Notifier."""

DEFAULT_ADSB_REQUEST_TIMEOUT_SECONDS = 10
DEFAULT_ADSB_POINT_RADIUS_MILES = 25.0
MAX_ADSB_POINT_RADIUS_MILES = 250.0

DEFAULT_API_PORT = 8000
DEFAULT_CONFIG_BACKUP_RETENTION = 20

DEFAULT_POLL_SECONDS = 30
DEFAULT_STALE_AIRCRAFT_SECONDS = 90
DEFAULT_RECENT_MATCHES_WINDOW_HOURS = 24
MAX_RECENT_MATCHES_WINDOW_HOURS = 168
MAX_RECENT_MATCHES = 200
DEFAULT_SOURCE_HEALTH_TREND_RETENTION_HOURS = 168
MAX_SOURCE_HEALTH_TREND_RETENTION_HOURS = 720

DEFAULT_RULE_RADIUS_MILES = 25.0
DEFAULT_RULE_COOLDOWN_MINUTES = 30
DEFAULT_QUIET_HOURS_START = "22:00"
DEFAULT_QUIET_HOURS_END = "07:00"
DEFAULT_QUIET_HOURS_TIME_ZONE = "America/Denver"
DEFAULT_CIRCLING_HEADING_CHANGE_DEG = 270.0
DEFAULT_CIRCLING_WINDOW_MINUTES = 8

DEFAULT_SOURCE_ERROR_ALERT_FAILURE_THRESHOLD = 3
DEFAULT_SOURCE_ERROR_ALERT_COOLDOWN_MINUTES = 60

DEFAULT_RATE_LIMIT_BACKOFF_SECONDS = 60
MAX_RATE_LIMIT_BACKOFF_SECONDS = 900
