image:
  registry: pi-lab-registry.local
  tag: latest

secret:
  create: false
  name: adsb-notifier-secrets

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: adsb-notifier.local
      paths:
        - path: /
          pathType: Prefix
    - host: adsb-notifier.10.0.0.100.sslip.io
      paths:
        - path: /
          pathType: Prefix
